# local coordinator used for testing / single node
# [coordinator.local]
# enabled = true

[coordinator.etcd]
enabled = true
hosts = ["etcd:2379"]

[signal]
fqdn = "localhost"
httpaddr = ":7000"
#grpcaddr = ":50050"
key = ""
cert = ""

[sfu.router]
# Limit the remb bandwidth in kbps
# zero means no limits
maxbandwidth = 1500
# max buffer time by ms for video tracks
maxbuffertime = 1000

[sfu.router.simulcast]
# Prefer best quality initially
bestqualityfirst = true
# EXPERIMENTAL enable temporal layer change is currently an experimental feature,
# enable only for testing.
enabletemporallayer = false

[sfu.webrtc]
# Range of ports that ion accepts WebRTC traffic on
# Format: [min, max]   and max - min >= 100
portrange = [5000, 5100]
# if sfu behind nat, set iceserver
# [[webrtc.iceserver]]
urls = ["stun:stun.stunprotocol.org:3478"]
# [[webrtc.iceserver]]
# urls = ["turn:turn.awsome.org:3478"]
# username = "awsome"
# credential = "awsome"
sdpsemantics = "unified-plan"

# In case you're deploying ion-sfu on a server which is configured with
# a 1:1 NAT (e.g., Amazon EC2), you might want to also specify the public
# address of the machine using the setting below. This will result in
# all host candidates (which normally have a private IP address) to
# be rewritten with the public address provided in the settings. As
# such, use the option with caution and only if you know what you're doing.
# Multiple public IP addresses can be specified as a comma separated list
# if the sfu is deployed in a DMZ between two 1-1 NAT for internal and
# external users.
# nat1to1 = ["1.2.3.4"]

[sfu.log]
stats = true
level = "debug"
fix = ["proc.go", "asm_amd64.s", "jsonrpc2.go"]
