version: "3.7"

services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.9
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379
    networks:
      - ionnet
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - "./cfgs/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - ionnet
  sfuA:
    image: pionwebrtc/ion-cluster:latest
    build:
      dockerfile: Dockerfile
      context: .
    command: ["-c", "/configs/sfu.toml", "-a", ":7000"]
    volumes:
      - "./cfgs/config-docker.toml:/configs/sfu.toml"
    environment:
      ION_CLUSTER_HOST: sfuA
    ports:
      - "5000-5100:5000-5100/udp"
      - "7000:7000"
    networks:
      - ionnet
  sfuB:
    image: pionwebrtc/ion-cluster:latest
    links:
      - sfuA
    build:
      dockerfile: Dockerfile
      context: .
    command: ["-c", "/configs/sfu.toml", "-a", ":7001"]
    volumes:
      - "./cfgs/config-docker.toml:/configs/sfu.toml"
    environment:
      ION_CLUSTER_HOST: sfuB
    ports:
      - "5200-5300:5200-5300/udp"
      - "7001:7001"
    networks:
      - ionnet

networks:
  ionnet:
    external: true
    name: ionnet
    driver: bridge

