apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
    serviceapp: ion-cluster-servicemonitor
  name: ion-cluster-servicemonitor
  namespace: default
spec:
  endpoints:
  - interval: 5s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: ion-sfu
